[versions]
agp = "8.4.0"
# library versions
appcompat = "1.6.1"
material = "1.11.0"
preference = "1.2.1"
annotation = "1.7.1"


[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
